Libraries

In [49]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [50]:
# configurations
data = {
    'Hours_Studied': [1, 2, 3, 4, 5, 7, 8, 10],
    'Test_Score':    [55, 62, 68, 70, 78, 85, 90, 95]
}
TARGET_COL = "Test_Score" # target column name

In [51]:
df = pd.DataFrame(data)
print("DataFrame shape:", df.shape)

#8 rows (samples/observations)
#2 columns (features/variables)

DataFrame shape: (8, 2)

In [52]:
df.head()

   Hours_Studied  Test_Score
0              1          55
1              2          62
2              3          68
3              4          70
4              5          78

In [53]:
df.columns

Index(['Hours_Studied', 'Test_Score'], dtype='object')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Hours_Studied  8 non-null      int64
 1   Test_Score     8 non-null      int64
dtypes: int64(2)
memory usage: 260.0 bytes

In [55]:
# separate features and target
X = df.drop(columns=[TARGET_COL])
y = df[TARGET_COL]

In [56]:
X.head()

   Hours_Studied
0              1
1              2
2              3
3              4
4              5

In [57]:
y.head()

0    55
1    62
2    68
3    70
4    78
Name: Test_Score, dtype: int64

In [58]:
# 1. Create a new, blank "brain" (model) from our recipe.
model = LinearRegression()

# 2. "Train" the brain.
# This is the most important line! We're telling the model
# to "fit" itself to our X and y data. It's looking at all
# the dots and figuring out the best line.
model.fit(X, y)

print("Done! The model has been trained.")

Done! The model has been trained.

In [59]:
# Let's see what the model learned!

# This is the 'b' (the Intercept)
intercept = model.intercept_

# This is the 'm' (the Slope)
# It's in an "array" (a list), so we grab the first item [0]
slope = model.coef_[0]

print(f"Model's Intercept (b): {intercept:.2f}")
print(f"Model's Slope (m): {slope:.2f}")

print(f"\nThis means the model learned the formula:")
print(f"Score = ({slope:.2f} * Hours_Studied) + {intercept:.2f}")

Model's Intercept (b): 53.10
Model's Slope (m): 4.46

This means the model learned the formula:
Score = (4.46 * Hours_Studied) + 53.10

In [60]:
# Let's predict a score for someone who studied for 6 hours.
# (Note: We have to give it the 6 in double brackets [[6]])

hours_to_predict = pd.DataFrame({'Hours_Studied': [6]})
predicted_score = model.predict(hours_to_predict)

print(f"The model predicts a score of {predicted_score[0]:.2f} for someone who studied 6 hours.")

# You can even check the math!
# (Slope * 6) + Intercept
math_check = (slope * 6) + intercept
print(f"Our manual math check: {math_check:.2f} (It matches!)")

The model predicts a score of 79.83 for someone who studied 6 hours.
Our manual math check: 79.83 (It matches!)

In [61]:
import joblib

# Save the model to a file
joblib.dump(model, 'test_score_model.pkl')

['test_score_model.pkl']